//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRecordMVC.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Records
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public Nullable<int> Class { get; set; }
        public string Result { get; set; }
    }
}
